package testutils

import (
	"time"

	"kisanlink-erp/internal/database/models"
)

// ========================================
// Test Data Factory Functions
// ========================================
// These functions create test data structures without database operations
// Following the e-commerce pattern for simple, fast unit tests

// ========================================
// Warehouse Fixtures
// ========================================

func FixtureWarehouse(name string) *models.Warehouse {
	warehouse := models.NewWarehouse(name, nil)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple warehouses
	return warehouse
}

func FixtureWarehouseWithID(id, name string) *models.Warehouse {
	warehouse := models.NewWarehouse(name, nil)
	warehouse.ID = id
	return warehouse
}

func FixtureWarehouseWithAddress(name, addressType, pincode string) *models.Warehouse {
	address := &models.CreateAddressRequest{
		Type:      addressType,
		Pincode:   &pincode,
		IsPrimary: true,
	}
	warehouse := models.NewWarehouseWithAddress(name, address)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple warehouses
	return warehouse
}

// ========================================
// Product Fixtures
// ========================================

func FixtureProduct(name string) *models.Product {
	desc := "Test product description"
	product := models.NewProduct(name, &desc)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple products
	return product
}

func FixtureProductWithID(id, name string) *models.Product {
	desc := "Test product description"
	product := models.NewProduct(name, &desc)
	product.ID = id
	return product
}

func FixtureProductWithExternalID(name, externalID string) *models.Product {
	product := FixtureProduct(name)
	product.ExternalID = &externalID
	return product
}

func FixtureProductWithCategory(name string, categoryID *string, subcategoryID *string) *models.Product {
	product := FixtureProduct(name)
	product.CategoryID = categoryID
	product.SubcategoryID = subcategoryID
	return product
}

// ========================================
// Category Fixtures
// ========================================

func FixtureCategory(name string) *models.Category {
	category := models.NewCategory(name, nil)
	return category
}

func FixtureCategoryWithID(id, name string) *models.Category {
	category := models.NewCategory(name, nil)
	category.ID = id
	return category
}

func FixtureCategoryWithDescription(name, description string) *models.Category {
	category := models.NewCategory(name, &description)
	return category
}

// ========================================
// Subcategory Fixtures
// ========================================

func FixtureSubcategory(name, categoryName string) *models.Subcategory {
	subcategory := models.NewSubcategory(name, categoryName, nil)
	return subcategory
}

func FixtureSubcategoryWithID(id, name, categoryName string) *models.Subcategory {
	subcategory := models.NewSubcategory(name, categoryName, nil)
	subcategory.ID = id
	return subcategory
}

func FixtureSubcategoryWithDescription(name, categoryName, description string) *models.Subcategory {
	subcategory := models.NewSubcategory(name, categoryName, &description)
	return subcategory
}

// ========================================
// ProductVariant Fixtures
// ========================================

func FixtureProductVariant(productID, variantName string) *models.ProductVariant {
	variant := models.NewProductVariant(productID, variantName, "1", "1kg")
	// Note: ID and SKU are auto-generated - don't hardcode to allow multiple variants
	// Generate unique SKU based on variant name to avoid conflicts
	sku := "SKU-" + variantName
	variant.SKU = &sku
	return variant
}

func FixtureProductVariantWithID(id, productID, variantName string) *models.ProductVariant {
	variant := models.NewProductVariant(productID, variantName, "1", "1kg")
	variant.ID = id
	sku := "SKU-" + id
	variant.SKU = &sku
	return variant
}

func FixtureProductVariantWithSKU(productID, variantName, sku string) *models.ProductVariant {
	variant := FixtureProductVariant(productID, variantName)
	variant.SKU = &sku
	return variant
}

// ========================================
// Inventory Batch Fixtures
// ========================================

func FixtureInventoryBatch(warehouseID, variantID string, quantity int64) *models.InventoryBatch {
	expiryDate := time.Now().AddDate(0, 6, 0) // 6 months from now
	batch := models.NewInventoryBatch(warehouseID, variantID, 100.0, expiryDate, quantity, 9.0, 9.0, []string{}, false)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple batches
	return batch
}

func FixtureInventoryBatchWithID(id, warehouseID, variantID string, quantity int64) *models.InventoryBatch {
	batch := FixtureInventoryBatch(warehouseID, variantID, quantity)
	batch.ID = id
	return batch
}

func FixtureInventoryBatchWithExpiry(warehouseID, variantID string, quantity int64, expiryDate time.Time) *models.InventoryBatch {
	batch := models.NewInventoryBatch(warehouseID, variantID, 100.0, expiryDate, quantity, 9.0, 9.0, []string{}, false)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple batches
	return batch
}

func FixtureInventoryBatchExpiring(warehouseID, variantID string, quantity int64, daysUntilExpiry int) *models.InventoryBatch {
	expiryDate := time.Now().AddDate(0, 0, daysUntilExpiry)
	batch := models.NewInventoryBatch(warehouseID, variantID, 100.0, expiryDate, quantity, 9.0, 9.0, []string{}, false)
	// Note: ID is auto-generated by BaseModel - don't set it to allow multiple batches
	return batch
}

// ========================================
// Inventory Transaction Fixtures
// ========================================

func FixtureInventoryTransaction(batchID, transactionType string, quantityChange int64) *models.InventoryTransaction {
	note := "Test transaction"
	transaction := models.NewInventoryTransaction(batchID, transactionType, quantityChange, nil, nil, &note, time.Now())
	transaction.ID = "TXN-TEST-001"
	return transaction
}

func FixtureInventoryTransactionWithID(id, batchID, transactionType string, quantityChange int64) *models.InventoryTransaction {
	transaction := FixtureInventoryTransaction(batchID, transactionType, quantityChange)
	transaction.ID = id
	return transaction
}

// ========================================
// Collaborator Fixtures
// ========================================

func FixtureCollaborator(name string) *models.Collaborator {
	contactNumber := "+91-9876543210"
	collaborator := models.NewCollaborator(name, name, contactNumber, "ACC123456", "IFSC0001234", nil)
	collaborator.ID = "COLLAB-TEST-001"
	return collaborator
}

func FixtureCollaboratorWithID(id, name string) *models.Collaborator {
	collaborator := FixtureCollaborator(name)
	collaborator.ID = id
	return collaborator
}

func FixtureCollaboratorWithGST(name, gstNumber string) *models.Collaborator {
	collaborator := FixtureCollaborator(name)
	collaborator.GSTNumber = gstNumber
	return collaborator
}

// ========================================
// Purchase Order Fixtures
// ========================================

func FixturePurchaseOrder(collaboratorID, warehouseID string, totalAmount float64) *models.PurchaseOrder {
	poNumber := "PO-TEST-001"
	po := models.NewPurchaseOrder(poNumber, collaboratorID, warehouseID, time.Now(), time.Now().AddDate(0, 0, 7))
	po.ID = "PO-TEST-001"
	po.TotalAmount = totalAmount
	po.Status = "placed"
	return po
}

func FixturePurchaseOrderWithID(id, poNumber, collaboratorID, warehouseID string, totalAmount float64) *models.PurchaseOrder {
	po := models.NewPurchaseOrder(poNumber, collaboratorID, warehouseID, time.Now(), time.Now().AddDate(0, 0, 7))
	po.ID = id
	po.TotalAmount = totalAmount
	po.Status = "placed"
	return po
}

func FixturePurchaseOrderWithStatus(collaboratorID, warehouseID, status string, totalAmount float64) *models.PurchaseOrder {
	po := FixturePurchaseOrder(collaboratorID, warehouseID, totalAmount)
	po.Status = status
	return po
}

func FixturePurchaseOrderWithItems(collaboratorID, warehouseID string, items []models.PurchaseOrderItem) *models.PurchaseOrder {
	po := FixturePurchaseOrder(collaboratorID, warehouseID, 0)
	po.Items = items

	// Calculate total amount from items
	totalAmount := 0.0
	for _, item := range items {
		totalAmount += item.LineTotal
	}
	po.TotalAmount = totalAmount

	return po
}

// ========================================
// Purchase Order Item Fixtures
// ========================================

func FixturePurchaseOrderItem(poID, variantID string, quantity int64, unitPrice float64) *models.PurchaseOrderItem {
	item := models.NewPurchaseOrderItem(poID, variantID, quantity, unitPrice)
	item.ID = "POITEM-TEST-001"
	return item
}

func FixturePurchaseOrderItemWithID(id, poID, variantID string, quantity int64, unitPrice float64) *models.PurchaseOrderItem {
	item := FixturePurchaseOrderItem(poID, variantID, quantity, unitPrice)
	item.ID = id
	return item
}

// ========================================
// GRN Fixtures
// ========================================

func FixtureGRN(purchaseOrderID, warehouseID string) *models.GRN {
	grnNumber := "GRN-TEST-001"
	grn := models.NewGRN(grnNumber, purchaseOrderID, warehouseID, "Test User", time.Now(), "pending")
	grn.ID = "GRN-TEST-001"
	return grn
}

func FixtureGRNWithID(id, grnNumber, purchaseOrderID, warehouseID string) *models.GRN {
	grn := models.NewGRN(grnNumber, purchaseOrderID, warehouseID, "Test User", time.Now(), "pending")
	grn.ID = id
	return grn
}

func FixtureGRNCompleted(purchaseOrderID, warehouseID string) *models.GRN {
	// GRN doesn't have a Status field, so we just return a regular GRN
	return FixtureGRN(purchaseOrderID, warehouseID)
}

func FixtureGRNWithItems(purchaseOrderID, warehouseID string, items []models.GRNItem) *models.GRN {
	grn := FixtureGRN(purchaseOrderID, warehouseID)
	grn.Items = items
	return grn
}

// ========================================
// GRN Item Fixtures
// ========================================

func FixtureGRNItem(grnID, poItemID, variantID string, quantity int64) *models.GRNItem {
	expiryDate := time.Now().AddDate(0, 6, 0) // 6 months from now
	item := models.NewGRNItem(grnID, poItemID, variantID, quantity, quantity, quantity, expiryDate)
	item.ID = "GRNITEM-TEST-001"
	return item
}

func FixtureGRNItemWithID(id, grnID, poItemID, variantID string, quantity int64) *models.GRNItem {
	item := FixtureGRNItem(grnID, poItemID, variantID, quantity)
	item.ID = id
	return item
}

// ========================================
// Sale Fixtures
// ========================================

func FixtureSale(warehouseID string, totalAmount float64) *models.Sale {
	sale := models.NewSale(warehouseID, time.Now(), totalAmount, "completed", nil, "cash", "in_store", false)
	sale.ID = "SALE-TEST-001"
	return sale
}

func FixtureSaleWithID(id, warehouseID string, totalAmount float64) *models.Sale {
	sale := FixtureSale(warehouseID, totalAmount)
	sale.ID = id
	return sale
}

func FixtureSaleWithStatus(warehouseID, status string, totalAmount float64) *models.Sale {
	sale := FixtureSale(warehouseID, totalAmount)
	sale.Status = status
	return sale
}

func FixtureSaleWithItems(warehouseID string, items []models.SaleItem) *models.Sale {
	totalAmount := 0.0
	for _, item := range items {
		totalAmount += item.LineTotal
	}
	sale := FixtureSale(warehouseID, totalAmount)
	sale.Items = items
	return sale
}

// ========================================
// Sale Item Fixtures
// ========================================

func FixtureSaleItem(saleID, variantID string, quantity int64, unitPrice float64) *models.SaleItem {
	item := models.NewSaleItem(saleID, variantID, quantity, unitPrice, 0, 0)
	item.ID = "SALEITEM-TEST-001"
	return item
}

func FixtureSaleItemWithID(id, saleID, variantID string, quantity int64, unitPrice float64) *models.SaleItem {
	item := FixtureSaleItem(saleID, variantID, quantity, unitPrice)
	item.ID = id
	return item
}

func FixtureSaleItemWithBatchID(saleID, variantID, batchID string, quantity int64, unitPrice float64) *models.SaleItem {
	item := FixtureSaleItem(saleID, variantID, quantity, unitPrice)
	item.BatchID = batchID
	return item
}

// ========================================
// Discount Fixtures
// ========================================

func FixtureDiscount(name, code string, discountType models.DiscountType, value float64) *models.Discount {
	desc := new(string)
	*desc = "Test discount"
	startDate := time.Now()
	endDate := time.Now().AddDate(0, 1, 0) // 1 month from now
	discount := models.NewDiscount(name, code, desc, discountType, value, startDate, endDate)
	discount.ID = "DISCOUNT-TEST-001"
	return discount
}

func FixtureDiscountWithID(id, name, code string, discountType models.DiscountType, value float64) *models.Discount {
	discount := FixtureDiscount(name, code, discountType, value)
	discount.ID = id
	return discount
}

func FixtureDiscountFlat(name, code string, value float64) *models.Discount {
	return FixtureDiscount(name, code, models.DiscountTypeFlat, value)
}

func FixtureDiscountPercentage(name, code string, value float64) *models.Discount {
	return FixtureDiscount(name, code, models.DiscountTypePercentage, value)
}

func FixtureDiscountWithDates(name, code string, discountType models.DiscountType, value float64, startDate, endDate time.Time) *models.Discount {
	desc := new(string)
	*desc = "Test discount"
	discount := models.NewDiscount(name, code, desc, discountType, value, startDate, endDate)
	discount.ID = "DISCOUNT-TEST-001"
	return discount
}

func FixtureDiscountWithUsageLimit(name, code string, discountType models.DiscountType, value float64, usageLimit int) *models.Discount {
	discount := FixtureDiscount(name, code, discountType, value)
	limit := usageLimit
	discount.UsageLimit = &limit
	return discount
}

func FixtureDiscountInactive(name, code string, discountType models.DiscountType, value float64) *models.Discount {
	discount := FixtureDiscount(name, code, discountType, value)
	discount.IsActive = false
	return discount
}

func FixtureDiscountExpired(name, code string, discountType models.DiscountType, value float64) *models.Discount {
	desc := new(string)
	*desc = "Test discount"
	startDate := time.Now().AddDate(0, -2, 0) // 2 months ago
	endDate := time.Now().AddDate(0, -1, 0)   // 1 month ago (expired)
	discount := models.NewDiscount(name, code, desc, discountType, value, startDate, endDate)
	discount.ID = "DISCOUNT-TEST-001"
	return discount
}

// ========================================
// Discount Usage Fixtures
// ========================================

func FixtureDiscountUsage(discountID, saleID string, amount float64) *models.DiscountUsage {
	usage := models.NewDiscountUsage(discountID, saleID, amount)
	usage.ID = "DISCUSAGE-TEST-001"
	return usage
}

func FixtureDiscountUsageWithID(id, discountID, saleID string, amount float64) *models.DiscountUsage {
	usage := FixtureDiscountUsage(discountID, saleID, amount)
	usage.ID = id
	return usage
}

// ========================================
// Tax Fixtures
// ========================================

func FixtureTax(name string, rate float64) *models.Tax {
	tax := models.NewTax()
	tax.ID = "TAX-TEST-001"
	tax.Name = name
	tax.Code = name
	tax.Rate = rate
	tax.IsActive = true
	return tax
}

func FixtureTaxWithID(id, name string, rate float64) *models.Tax {
	tax := FixtureTax(name, rate)
	tax.ID = id
	return tax
}

func FixtureTaxGST() *models.Tax {
	return FixtureTax("GST", 18.0)
}

func FixtureTaxCGST() *models.Tax {
	return FixtureTax("CGST", 9.0)
}

func FixtureTaxSGST() *models.Tax {
	return FixtureTax("SGST", 9.0)
}

// ========================================
// ProductPrice Fixtures
// ========================================

// FixtureProductPrice creates an in-memory ProductPrice
func FixtureProductPrice(variantID, priceType string, price float64) *models.ProductPrice {
	effectiveFrom := time.Now().UTC()
	isActive := true
	return models.NewProductPrice(variantID, priceType, price, "INR", effectiveFrom, nil, &isActive)
}

// FixtureProductPriceWithDates creates a ProductPrice with custom dates
func FixtureProductPriceWithDates(variantID, priceType string, price float64, effectiveFrom time.Time, effectiveTo *time.Time) *models.ProductPrice {
	isActive := true
	return models.NewProductPrice(variantID, priceType, price, "INR", effectiveFrom, effectiveTo, &isActive)
}

// FixtureProductPriceExpired creates an expired ProductPrice
func FixtureProductPriceExpired(variantID, priceType string, price float64) *models.ProductPrice {
	effectiveFrom := time.Now().UTC().Add(-30 * 24 * time.Hour) // 30 days ago
	effectiveTo := time.Now().UTC().Add(-1 * 24 * time.Hour)    // Yesterday
	isActive := true
	return models.NewProductPrice(variantID, priceType, price, "INR", effectiveFrom, &effectiveTo, &isActive)
}

// FixtureProductPriceInactive creates an inactive ProductPrice
func FixtureProductPriceInactive(variantID, priceType string, price float64) *models.ProductPrice {
	effectiveFrom := time.Now().UTC()
	isActive := false
	return models.NewProductPrice(variantID, priceType, price, "INR", effectiveFrom, nil, &isActive)
}

// ========================================
// Return Fixtures
// ========================================

func FixtureReturn(saleID string, totalRefund float64) *models.Return {
	returnDate := time.Now()
	status := "pending"
	return models.NewReturn(saleID, returnDate, totalRefund, status)
}

func FixtureReturnWithID(id, saleID string, totalRefund float64) *models.Return {
	ret := FixtureReturn(saleID, totalRefund)
	ret.ID = id
	return ret
}

func FixtureReturnWithStatus(saleID, status string, totalRefund float64) *models.Return {
	returnDate := time.Now()
	return models.NewReturn(saleID, returnDate, totalRefund, status)
}

func FixtureReturnWithItems(saleID string, items []models.ReturnItem) *models.Return {
	totalRefund := 0.0
	for _, item := range items {
		totalRefund += item.RefundAmount
	}
	ret := FixtureReturn(saleID, totalRefund)
	ret.Items = items
	return ret
}

// ========================================
// Return Item Fixtures
// ========================================

func FixtureReturnItem(returnID, batchID string, quantity int64, refundAmount float64) *models.ReturnItem {
	return models.NewReturnItem(returnID, batchID, quantity, refundAmount)
}

func FixtureReturnItemWithID(id, returnID, batchID string, quantity int64, refundAmount float64) *models.ReturnItem {
	item := FixtureReturnItem(returnID, batchID, quantity, refundAmount)
	item.ID = id
	return item
}
