package utils

import (
	"errors"

	"github.com/golang-jwt/jwt/v5"
)

// OrganizationContext represents organization data in JWT claims
type OrganizationContext struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

// GroupContext represents group data in JWT claims
type GroupContext struct {
	ID             string `json:"id"`
	Name           string `json:"name"`
	OrganizationID string `json:"organization_id"`
}

// RoleContext represents role data in JWT claims
type RoleContext struct {
	ID             string  `json:"id"`
	Name           string  `json:"name"`
	Scope          string  `json:"scope"`
	OrganizationID *string `json:"organization_id,omitempty"`
	GroupID        *string `json:"group_id,omitempty"`
	IsActive       bool    `json:"is_active"`
}

// UserContextClaims represents user information in JWT
type UserContextClaims struct {
	ID          string `json:"id"`
	Username    string `json:"username"`
	PhoneNumber string `json:"phone_number"`
	CountryCode string `json:"country_code"`
	IsValidated bool   `json:"is_validated"`
}

// CustomClaims extends JWT standard claims with AAA service context
// This structure matches the JWT tokens generated by AAA service LoginV2
type CustomClaims struct {
	UserContext   UserContextClaims     `json:"user_context"`
	Roles         []RoleContext         `json:"roles"`
	Organizations []OrganizationContext `json:"organizations"`
	Groups        []GroupContext        `json:"groups"`
	Permissions   []string              `json:"permissions"`
	Scopes        []string              `json:"scopes"`
	TenantContext map[string][]string   `json:"tenant_context,omitempty"`
	SessionID     string                `json:"session_id,omitempty"`
	TokenType     string                `json:"token_type"`
	TokenVersion  string                `json:"token_version,omitempty"`
	jwt.RegisteredClaims
}

// GetUserOrganizations extracts all organization IDs from JWT claims
// Combines organization IDs from both roles and direct memberships
func GetUserOrganizations(claims *CustomClaims) []string {
	orgMap := make(map[string]bool)

	// Get organization IDs from roles with organization scope
	for _, role := range claims.Roles {
		if role.OrganizationID != nil && *role.OrganizationID != "" {
			orgMap[*role.OrganizationID] = true
		}
	}

	// Get organization IDs from direct organization memberships
	for _, org := range claims.Organizations {
		if org.ID != "" {
			orgMap[org.ID] = true
		}
	}

	// Convert map to array
	orgs := make([]string, 0, len(orgMap))
	for orgID := range orgMap {
		orgs = append(orgs, orgID)
	}

	return orgs
}

// GetPrimaryOrganizationID extracts the primary organization ID
// For single-organization users, they should have exactly ONE organization
// Returns the organization ID
func GetPrimaryOrganizationID(claims *CustomClaims) (string, error) {
	orgs := GetUserOrganizations(claims)

	if len(orgs) == 0 {
		return "", errors.New("no organizations found in token - user may not be associated with any organization")
	}

	if len(orgs) > 1 {
		// Log warning: user belongs to multiple organizations
		// This may be valid for super admins or users with multiple org memberships
		// Return first organization as primary
		return orgs[0], nil
	}

	// Single organization - return the organization ID
	return orgs[0], nil
}

// HasOrganizationAccess checks if user has access to a specific organization
// Validates both role-based and direct membership-based access
func HasOrganizationAccess(claims *CustomClaims, organizationID string) bool {
	// Check if user has any active role scoped to this organization
	for _, role := range claims.Roles {
		if role.IsActive && role.OrganizationID != nil && *role.OrganizationID == organizationID {
			return true
		}
	}

	// Check if user has direct membership in this organization
	for _, org := range claims.Organizations {
		if org.ID == organizationID {
			return true
		}
	}

	return false
}

// GetUserGroups extracts all group IDs from JWT claims
func GetUserGroups(claims *CustomClaims) []string {
	groupMap := make(map[string]bool)

	// Get group IDs from roles with group scope
	for _, role := range claims.Roles {
		if role.GroupID != nil && *role.GroupID != "" {
			groupMap[*role.GroupID] = true
		}
	}

	// Get group IDs from direct group memberships
	for _, group := range claims.Groups {
		if group.ID != "" {
			groupMap[group.ID] = true
		}
	}

	// Convert map to array
	groups := make([]string, 0, len(groupMap))
	for groupID := range groupMap {
		groups = append(groups, groupID)
	}

	return groups
}

// HasGroupAccess checks if user has access to a specific group
func HasGroupAccess(claims *CustomClaims, groupID string) bool {
	// Check if user has any active role scoped to this group
	for _, role := range claims.Roles {
		if role.IsActive && role.GroupID != nil && *role.GroupID == groupID {
			return true
		}
	}

	// Check if user has direct membership in this group
	for _, group := range claims.Groups {
		if group.ID == groupID {
			return true
		}
	}

	return false
}

// HasPermission checks if user has a specific permission
func HasPermission(claims *CustomClaims, permission string) bool {
	for _, perm := range claims.Permissions {
		if perm == permission {
			return true
		}
	}
	return false
}

// HasScope checks if user has a specific scope
func HasScope(claims *CustomClaims, scope string) bool {
	for _, s := range claims.Scopes {
		if s == scope {
			return true
		}
	}
	return false
}

// GetOrganizationName returns the name of the primary organization
func GetOrganizationName(claims *CustomClaims) string {
	if len(claims.Organizations) == 0 {
		return ""
	}
	return claims.Organizations[0].Name
}

// GetActiveRoles returns all active roles for the user
func GetActiveRoles(claims *CustomClaims) []RoleContext {
	activeRoles := make([]RoleContext, 0)
	for _, role := range claims.Roles {
		if role.IsActive {
			activeRoles = append(activeRoles, role)
		}
	}
	return activeRoles
}

// GetRoleNames returns names of all active roles
func GetRoleNames(claims *CustomClaims) []string {
	activeRoles := GetActiveRoles(claims)
	names := make([]string, len(activeRoles))
	for i, role := range activeRoles {
		names[i] = role.Name
	}
	return names
}

// HasRole checks if user has a specific role (by name)
func HasRole(claims *CustomClaims, roleName string) bool {
	for _, role := range claims.Roles {
		if role.IsActive && role.Name == roleName {
			return true
		}
	}
	return false
}
