// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/address.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Address represents an address entity
type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // HOME, WORK, OTHER
	House         *string                `protobuf:"bytes,4,opt,name=house,proto3,oneof" json:"house,omitempty"`
	Street        *string                `protobuf:"bytes,5,opt,name=street,proto3,oneof" json:"street,omitempty"`
	Landmark      *string                `protobuf:"bytes,6,opt,name=landmark,proto3,oneof" json:"landmark,omitempty"`
	PostOffice    *string                `protobuf:"bytes,7,opt,name=post_office,json=postOffice,proto3,oneof" json:"post_office,omitempty"`
	Subdistrict   *string                `protobuf:"bytes,8,opt,name=subdistrict,proto3,oneof" json:"subdistrict,omitempty"`
	District      *string                `protobuf:"bytes,9,opt,name=district,proto3,oneof" json:"district,omitempty"`
	Vtc           *string                `protobuf:"bytes,10,opt,name=vtc,proto3,oneof" json:"vtc,omitempty"` // Village/Town/City
	State         *string                `protobuf:"bytes,11,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       *string                `protobuf:"bytes,12,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Pincode       *string                `protobuf:"bytes,13,opt,name=pincode,proto3,oneof" json:"pincode,omitempty"`
	FullAddress   *string                `protobuf:"bytes,14,opt,name=full_address,json=fullAddress,proto3,oneof" json:"full_address,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,15,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	IsActive      bool                   `protobuf:"varint,16,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_proto_address_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Address) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Address) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil && x.House != nil {
		return *x.House
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *Address) GetLandmark() string {
	if x != nil && x.Landmark != nil {
		return *x.Landmark
	}
	return ""
}

func (x *Address) GetPostOffice() string {
	if x != nil && x.PostOffice != nil {
		return *x.PostOffice
	}
	return ""
}

func (x *Address) GetSubdistrict() string {
	if x != nil && x.Subdistrict != nil {
		return *x.Subdistrict
	}
	return ""
}

func (x *Address) GetDistrict() string {
	if x != nil && x.District != nil {
		return *x.District
	}
	return ""
}

func (x *Address) GetVtc() string {
	if x != nil && x.Vtc != nil {
		return *x.Vtc
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *Address) GetPincode() string {
	if x != nil && x.Pincode != nil {
		return *x.Pincode
	}
	return ""
}

func (x *Address) GetFullAddress() string {
	if x != nil && x.FullAddress != nil {
		return *x.FullAddress
	}
	return ""
}

func (x *Address) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Address) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Address) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Address) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateAddressRequest represents a request to create an address
type CreateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	House         *string                `protobuf:"bytes,3,opt,name=house,proto3,oneof" json:"house,omitempty"`
	Street        *string                `protobuf:"bytes,4,opt,name=street,proto3,oneof" json:"street,omitempty"`
	Landmark      *string                `protobuf:"bytes,5,opt,name=landmark,proto3,oneof" json:"landmark,omitempty"`
	PostOffice    *string                `protobuf:"bytes,6,opt,name=post_office,json=postOffice,proto3,oneof" json:"post_office,omitempty"`
	Subdistrict   *string                `protobuf:"bytes,7,opt,name=subdistrict,proto3,oneof" json:"subdistrict,omitempty"`
	District      *string                `protobuf:"bytes,8,opt,name=district,proto3,oneof" json:"district,omitempty"`
	Vtc           *string                `protobuf:"bytes,9,opt,name=vtc,proto3,oneof" json:"vtc,omitempty"`
	State         *string                `protobuf:"bytes,10,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       *string                `protobuf:"bytes,11,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Pincode       *string                `protobuf:"bytes,12,opt,name=pincode,proto3,oneof" json:"pincode,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,13,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAddressRequest) Reset() {
	*x = CreateAddressRequest{}
	mi := &file_proto_address_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAddressRequest) ProtoMessage() {}

func (x *CreateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAddressRequest.ProtoReflect.Descriptor instead.
func (*CreateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAddressRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateAddressRequest) GetHouse() string {
	if x != nil && x.House != nil {
		return *x.House
	}
	return ""
}

func (x *CreateAddressRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *CreateAddressRequest) GetLandmark() string {
	if x != nil && x.Landmark != nil {
		return *x.Landmark
	}
	return ""
}

func (x *CreateAddressRequest) GetPostOffice() string {
	if x != nil && x.PostOffice != nil {
		return *x.PostOffice
	}
	return ""
}

func (x *CreateAddressRequest) GetSubdistrict() string {
	if x != nil && x.Subdistrict != nil {
		return *x.Subdistrict
	}
	return ""
}

func (x *CreateAddressRequest) GetDistrict() string {
	if x != nil && x.District != nil {
		return *x.District
	}
	return ""
}

func (x *CreateAddressRequest) GetVtc() string {
	if x != nil && x.Vtc != nil {
		return *x.Vtc
	}
	return ""
}

func (x *CreateAddressRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *CreateAddressRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *CreateAddressRequest) GetPincode() string {
	if x != nil && x.Pincode != nil {
		return *x.Pincode
	}
	return ""
}

func (x *CreateAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

// GetAddressRequest represents a request to get an address by ID
type GetAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAddressRequest) Reset() {
	*x = GetAddressRequest{}
	mi := &file_proto_address_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAddressRequest) ProtoMessage() {}

func (x *GetAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAddressRequest.ProtoReflect.Descriptor instead.
func (*GetAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{2}
}

func (x *GetAddressRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

// UpdateAddressRequest represents a request to update an address
type UpdateAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	House         *string                `protobuf:"bytes,3,opt,name=house,proto3,oneof" json:"house,omitempty"`
	Street        *string                `protobuf:"bytes,4,opt,name=street,proto3,oneof" json:"street,omitempty"`
	Landmark      *string                `protobuf:"bytes,5,opt,name=landmark,proto3,oneof" json:"landmark,omitempty"`
	PostOffice    *string                `protobuf:"bytes,6,opt,name=post_office,json=postOffice,proto3,oneof" json:"post_office,omitempty"`
	Subdistrict   *string                `protobuf:"bytes,7,opt,name=subdistrict,proto3,oneof" json:"subdistrict,omitempty"`
	District      *string                `protobuf:"bytes,8,opt,name=district,proto3,oneof" json:"district,omitempty"`
	Vtc           *string                `protobuf:"bytes,9,opt,name=vtc,proto3,oneof" json:"vtc,omitempty"`
	State         *string                `protobuf:"bytes,10,opt,name=state,proto3,oneof" json:"state,omitempty"`
	Country       *string                `protobuf:"bytes,11,opt,name=country,proto3,oneof" json:"country,omitempty"`
	Pincode       *string                `protobuf:"bytes,12,opt,name=pincode,proto3,oneof" json:"pincode,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,13,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	IsActive      bool                   `protobuf:"varint,14,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAddressRequest) Reset() {
	*x = UpdateAddressRequest{}
	mi := &file_proto_address_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAddressRequest) ProtoMessage() {}

func (x *UpdateAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAddressRequest.ProtoReflect.Descriptor instead.
func (*UpdateAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateAddressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAddressRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateAddressRequest) GetHouse() string {
	if x != nil && x.House != nil {
		return *x.House
	}
	return ""
}

func (x *UpdateAddressRequest) GetStreet() string {
	if x != nil && x.Street != nil {
		return *x.Street
	}
	return ""
}

func (x *UpdateAddressRequest) GetLandmark() string {
	if x != nil && x.Landmark != nil {
		return *x.Landmark
	}
	return ""
}

func (x *UpdateAddressRequest) GetPostOffice() string {
	if x != nil && x.PostOffice != nil {
		return *x.PostOffice
	}
	return ""
}

func (x *UpdateAddressRequest) GetSubdistrict() string {
	if x != nil && x.Subdistrict != nil {
		return *x.Subdistrict
	}
	return ""
}

func (x *UpdateAddressRequest) GetDistrict() string {
	if x != nil && x.District != nil {
		return *x.District
	}
	return ""
}

func (x *UpdateAddressRequest) GetVtc() string {
	if x != nil && x.Vtc != nil {
		return *x.Vtc
	}
	return ""
}

func (x *UpdateAddressRequest) GetState() string {
	if x != nil && x.State != nil {
		return *x.State
	}
	return ""
}

func (x *UpdateAddressRequest) GetCountry() string {
	if x != nil && x.Country != nil {
		return *x.Country
	}
	return ""
}

func (x *UpdateAddressRequest) GetPincode() string {
	if x != nil && x.Pincode != nil {
		return *x.Pincode
	}
	return ""
}

func (x *UpdateAddressRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *UpdateAddressRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

// DeleteAddressRequest represents a request to delete an address
type DeleteAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressId     string                 `protobuf:"bytes,1,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	SoftDelete    bool                   `protobuf:"varint,2,opt,name=soft_delete,json=softDelete,proto3" json:"soft_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressRequest) Reset() {
	*x = DeleteAddressRequest{}
	mi := &file_proto_address_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressRequest) ProtoMessage() {}

func (x *DeleteAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressRequest.ProtoReflect.Descriptor instead.
func (*DeleteAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteAddressRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *DeleteAddressRequest) GetSoftDelete() bool {
	if x != nil {
		return x.SoftDelete
	}
	return false
}

// SearchAddressesRequest represents a request to search addresses
type SearchAddressesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAddressesRequest) Reset() {
	*x = SearchAddressesRequest{}
	mi := &file_proto_address_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAddressesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAddressesRequest) ProtoMessage() {}

func (x *SearchAddressesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAddressesRequest.ProtoReflect.Descriptor instead.
func (*SearchAddressesRequest) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{5}
}

func (x *SearchAddressesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchAddressesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchAddressesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// AddressResponse represents a response containing an address
type AddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          *Address               `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddressResponse) Reset() {
	*x = AddressResponse{}
	mi := &file_proto_address_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressResponse) ProtoMessage() {}

func (x *AddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressResponse.ProtoReflect.Descriptor instead.
func (*AddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{6}
}

func (x *AddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *AddressResponse) GetData() *Address {
	if x != nil {
		return x.Data
	}
	return nil
}

// DeleteAddressResponse represents a response for delete operation
type DeleteAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAddressResponse) Reset() {
	*x = DeleteAddressResponse{}
	mi := &file_proto_address_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAddressResponse) ProtoMessage() {}

func (x *DeleteAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAddressResponse.ProtoReflect.Descriptor instead.
func (*DeleteAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteAddressResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteAddressResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteAddressResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

// SearchAddressesResponse represents a response containing multiple addresses
type SearchAddressesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Data          []*Address             `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	TotalCount    int32                  `protobuf:"varint,5,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchAddressesResponse) Reset() {
	*x = SearchAddressesResponse{}
	mi := &file_proto_address_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchAddressesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchAddressesResponse) ProtoMessage() {}

func (x *SearchAddressesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_address_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchAddressesResponse.ProtoReflect.Descriptor instead.
func (*SearchAddressesResponse) Descriptor() ([]byte, []int) {
	return file_proto_address_proto_rawDescGZIP(), []int{8}
}

func (x *SearchAddressesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SearchAddressesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SearchAddressesResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *SearchAddressesResponse) GetData() []*Address {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SearchAddressesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_proto_address_proto protoreflect.FileDescriptor

const file_proto_address_proto_rawDesc = "" +
	"\n" +
	"\x13proto/address.proto\x12\x02pb\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe1\x05\n" +
	"\aAddress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x19\n" +
	"\x05house\x18\x04 \x01(\tH\x00R\x05house\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x05 \x01(\tH\x01R\x06street\x88\x01\x01\x12\x1f\n" +
	"\blandmark\x18\x06 \x01(\tH\x02R\blandmark\x88\x01\x01\x12$\n" +
	"\vpost_office\x18\a \x01(\tH\x03R\n" +
	"postOffice\x88\x01\x01\x12%\n" +
	"\vsubdistrict\x18\b \x01(\tH\x04R\vsubdistrict\x88\x01\x01\x12\x1f\n" +
	"\bdistrict\x18\t \x01(\tH\x05R\bdistrict\x88\x01\x01\x12\x15\n" +
	"\x03vtc\x18\n" +
	" \x01(\tH\x06R\x03vtc\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\v \x01(\tH\aR\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\f \x01(\tH\bR\acountry\x88\x01\x01\x12\x1d\n" +
	"\apincode\x18\r \x01(\tH\tR\apincode\x88\x01\x01\x12&\n" +
	"\ffull_address\x18\x0e \x01(\tH\n" +
	"R\vfullAddress\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x0f \x01(\bR\tisPrimary\x12\x1b\n" +
	"\tis_active\x18\x10 \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\b\n" +
	"\x06_houseB\t\n" +
	"\a_streetB\v\n" +
	"\t_landmarkB\x0e\n" +
	"\f_post_officeB\x0e\n" +
	"\f_subdistrictB\v\n" +
	"\t_districtB\x06\n" +
	"\x04_vtcB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\n" +
	"\n" +
	"\b_pincodeB\x0f\n" +
	"\r_full_address\"\x92\x04\n" +
	"\x14CreateAddressRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05house\x18\x03 \x01(\tH\x00R\x05house\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x04 \x01(\tH\x01R\x06street\x88\x01\x01\x12\x1f\n" +
	"\blandmark\x18\x05 \x01(\tH\x02R\blandmark\x88\x01\x01\x12$\n" +
	"\vpost_office\x18\x06 \x01(\tH\x03R\n" +
	"postOffice\x88\x01\x01\x12%\n" +
	"\vsubdistrict\x18\a \x01(\tH\x04R\vsubdistrict\x88\x01\x01\x12\x1f\n" +
	"\bdistrict\x18\b \x01(\tH\x05R\bdistrict\x88\x01\x01\x12\x15\n" +
	"\x03vtc\x18\t \x01(\tH\x06R\x03vtc\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\n" +
	" \x01(\tH\aR\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\v \x01(\tH\bR\acountry\x88\x01\x01\x12\x1d\n" +
	"\apincode\x18\f \x01(\tH\tR\apincode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\r \x01(\bR\tisPrimaryB\b\n" +
	"\x06_houseB\t\n" +
	"\a_streetB\v\n" +
	"\t_landmarkB\x0e\n" +
	"\f_post_officeB\x0e\n" +
	"\f_subdistrictB\v\n" +
	"\t_districtB\x06\n" +
	"\x04_vtcB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\n" +
	"\n" +
	"\b_pincode\"2\n" +
	"\x11GetAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\"\xa6\x04\n" +
	"\x14UpdateAddressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\x05house\x18\x03 \x01(\tH\x00R\x05house\x88\x01\x01\x12\x1b\n" +
	"\x06street\x18\x04 \x01(\tH\x01R\x06street\x88\x01\x01\x12\x1f\n" +
	"\blandmark\x18\x05 \x01(\tH\x02R\blandmark\x88\x01\x01\x12$\n" +
	"\vpost_office\x18\x06 \x01(\tH\x03R\n" +
	"postOffice\x88\x01\x01\x12%\n" +
	"\vsubdistrict\x18\a \x01(\tH\x04R\vsubdistrict\x88\x01\x01\x12\x1f\n" +
	"\bdistrict\x18\b \x01(\tH\x05R\bdistrict\x88\x01\x01\x12\x15\n" +
	"\x03vtc\x18\t \x01(\tH\x06R\x03vtc\x88\x01\x01\x12\x19\n" +
	"\x05state\x18\n" +
	" \x01(\tH\aR\x05state\x88\x01\x01\x12\x1d\n" +
	"\acountry\x18\v \x01(\tH\bR\acountry\x88\x01\x01\x12\x1d\n" +
	"\apincode\x18\f \x01(\tH\tR\apincode\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"is_primary\x18\r \x01(\bR\tisPrimary\x12\x1b\n" +
	"\tis_active\x18\x0e \x01(\bR\bisActiveB\b\n" +
	"\x06_houseB\t\n" +
	"\a_streetB\v\n" +
	"\t_landmarkB\x0e\n" +
	"\f_post_officeB\x0e\n" +
	"\f_subdistrictB\v\n" +
	"\t_districtB\x06\n" +
	"\x04_vtcB\b\n" +
	"\x06_stateB\n" +
	"\n" +
	"\b_countryB\n" +
	"\n" +
	"\b_pincode\"V\n" +
	"\x14DeleteAddressRequest\x12\x1d\n" +
	"\n" +
	"address_id\x18\x01 \x01(\tR\taddressId\x12\x1f\n" +
	"\vsoft_delete\x18\x02 \x01(\bR\n" +
	"softDelete\"\\\n" +
	"\x16SearchAddressesRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\x87\x01\n" +
	"\x0fAddressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\x04data\x18\x04 \x01(\v2\v.pb.AddressR\x04data\"l\n" +
	"\x15DeleteAddressResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\"\xb0\x01\n" +
	"\x17SearchAddressesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\x04data\x18\x04 \x03(\v2\v.pb.AddressR\x04data\x12\x1f\n" +
	"\vtotal_count\x18\x05 \x01(\x05R\n" +
	"totalCount2\xdc\x02\n" +
	"\x0eAddressService\x12>\n" +
	"\rCreateAddress\x12\x18.pb.CreateAddressRequest\x1a\x13.pb.AddressResponse\x128\n" +
	"\n" +
	"GetAddress\x12\x15.pb.GetAddressRequest\x1a\x13.pb.AddressResponse\x12>\n" +
	"\rUpdateAddress\x12\x18.pb.UpdateAddressRequest\x1a\x13.pb.AddressResponse\x12D\n" +
	"\rDeleteAddress\x12\x18.pb.DeleteAddressRequest\x1a\x19.pb.DeleteAddressResponse\x12J\n" +
	"\x0fSearchAddresses\x12\x1a.pb.SearchAddressesRequest\x1a\x1b.pb.SearchAddressesResponseB\x19Z\x17kisanlink-erp/pkg/protob\x06proto3"

var (
	file_proto_address_proto_rawDescOnce sync.Once
	file_proto_address_proto_rawDescData []byte
)

func file_proto_address_proto_rawDescGZIP() []byte {
	file_proto_address_proto_rawDescOnce.Do(func() {
		file_proto_address_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_address_proto_rawDesc), len(file_proto_address_proto_rawDesc)))
	})
	return file_proto_address_proto_rawDescData
}

var file_proto_address_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_address_proto_goTypes = []any{
	(*Address)(nil),                 // 0: pb.Address
	(*CreateAddressRequest)(nil),    // 1: pb.CreateAddressRequest
	(*GetAddressRequest)(nil),       // 2: pb.GetAddressRequest
	(*UpdateAddressRequest)(nil),    // 3: pb.UpdateAddressRequest
	(*DeleteAddressRequest)(nil),    // 4: pb.DeleteAddressRequest
	(*SearchAddressesRequest)(nil),  // 5: pb.SearchAddressesRequest
	(*AddressResponse)(nil),         // 6: pb.AddressResponse
	(*DeleteAddressResponse)(nil),   // 7: pb.DeleteAddressResponse
	(*SearchAddressesResponse)(nil), // 8: pb.SearchAddressesResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_proto_address_proto_depIdxs = []int32{
	9, // 0: pb.Address.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: pb.Address.updated_at:type_name -> google.protobuf.Timestamp
	0, // 2: pb.AddressResponse.data:type_name -> pb.Address
	0, // 3: pb.SearchAddressesResponse.data:type_name -> pb.Address
	1, // 4: pb.AddressService.CreateAddress:input_type -> pb.CreateAddressRequest
	2, // 5: pb.AddressService.GetAddress:input_type -> pb.GetAddressRequest
	3, // 6: pb.AddressService.UpdateAddress:input_type -> pb.UpdateAddressRequest
	4, // 7: pb.AddressService.DeleteAddress:input_type -> pb.DeleteAddressRequest
	5, // 8: pb.AddressService.SearchAddresses:input_type -> pb.SearchAddressesRequest
	6, // 9: pb.AddressService.CreateAddress:output_type -> pb.AddressResponse
	6, // 10: pb.AddressService.GetAddress:output_type -> pb.AddressResponse
	6, // 11: pb.AddressService.UpdateAddress:output_type -> pb.AddressResponse
	7, // 12: pb.AddressService.DeleteAddress:output_type -> pb.DeleteAddressResponse
	8, // 13: pb.AddressService.SearchAddresses:output_type -> pb.SearchAddressesResponse
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_address_proto_init() }
func file_proto_address_proto_init() {
	if File_proto_address_proto != nil {
		return
	}
	file_proto_address_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_address_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_address_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_address_proto_rawDesc), len(file_proto_address_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_address_proto_goTypes,
		DependencyIndexes: file_proto_address_proto_depIdxs,
		MessageInfos:      file_proto_address_proto_msgTypes,
	}.Build()
	File_proto_address_proto = out.File
	file_proto_address_proto_goTypes = nil
	file_proto_address_proto_depIdxs = nil
}
